import { MigrationInterface, QueryRunner } from "typeorm";

export class Auto1762531840865 implements MigrationInterface {
    name = 'Auto1762531840865'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "sprints" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "sprint_name" character varying NOT NULL, "goal" text, "start_date" TIMESTAMP, "end_date" TIMESTAMP, "duration_days" integer, "status" character varying NOT NULL, CONSTRAINT "PK_6800aa2e0f508561812c4b9afb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprint_issues" ("sprint_id" integer NOT NULL, "issue_id" integer NOT NULL, "rank_order" integer, CONSTRAINT "PK_14ea8d57167fbfb24774c401b48" PRIMARY KEY ("sprint_id", "issue_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_14ea8d57167fbfb24774c401b4" ON "sprint_issues" ("sprint_id", "issue_id") `);
        await queryRunner.query(`CREATE TABLE "issue_types" ("id" SERIAL NOT NULL, "type_name" character varying NOT NULL, CONSTRAINT "UQ_c627a437a238428ebd2c9f0b4d7" UNIQUE ("type_name"), CONSTRAINT "PK_24907560935389ac8139cee3f85" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workflows" ("id" SERIAL NOT NULL, "workflow_name" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_29684cccd5d9bbefb20cb92466e" UNIQUE ("workflow_name"), CONSTRAINT "PK_5b5757cc1cd86268019fef52e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workflow_statuses" ("id" SERIAL NOT NULL, "workflow_id" integer NOT NULL, "status_name" character varying NOT NULL, "status_category" character varying, "is_initial_status" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_5933af9b773c575a905467543f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_38b7a83f7dad794d535bb1c82d" ON "workflow_statuses" ("workflow_id", "status_name") `);
        await queryRunner.query(`CREATE TABLE "workflow_scheme_mappings" ("workflow_scheme_id" integer NOT NULL, "issue_type_id" integer NOT NULL, "workflow_id" integer NOT NULL, CONSTRAINT "PK_3ff2c1c4c5668bda6cadc4eca8d" PRIMARY KEY ("workflow_scheme_id", "issue_type_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3ff2c1c4c5668bda6cadc4eca8" ON "workflow_scheme_mappings" ("workflow_scheme_id", "issue_type_id") `);
        await queryRunner.query(`CREATE TABLE "epics" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "epic_name" character varying NOT NULL, "goal" text, "status" character varying, "start_date" date, "due_date" date, CONSTRAINT "PK_aa782b1b14b73c7a38f04b71e3f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "issues" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "issue_type_id" integer NOT NULL, "summary" character varying NOT NULL, "description" text, "current_status_id" integer NOT NULL, "reporter_id" bigint NOT NULL, "epic_link_id" integer, "story_points" integer, "original_estimate_seconds" integer, "time_spent_seconds" integer, "resolution" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9d8ecbbeff46229c700f0449257" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "issue_links" ("id" SERIAL NOT NULL, "source_issue_id" integer NOT NULL, "target_issue_id" integer NOT NULL, "link_type" character varying NOT NULL, CONSTRAINT "PK_92c961bad3a83cebd040a61d87f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "issue_comments" ("id" SERIAL NOT NULL, "issue_id" integer NOT NULL, "employee_id" bigint NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c650a2d6817045a0c8ce74f09f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "issue_change_histories" ("id" SERIAL NOT NULL, "issue_id" integer NOT NULL, "changer_employee_id" bigint NOT NULL, "change_date" TIMESTAMP NOT NULL, "field_name" character varying NOT NULL, "old_value" character varying, "new_value" character varying, CONSTRAINT "PK_4a3b52726e1bcdf4a21ec5270f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_schemes" ("id" SERIAL NOT NULL, "scheme_name" character varying NOT NULL, "scheme_description" character varying, CONSTRAINT "UQ_da94bdf01d2a801f3a34692758a" UNIQUE ("scheme_name"), CONSTRAINT "PK_160024a02eb60517fe964838c12" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "notification_scheme_id" integer NOT NULL, "event_name" character varying NOT NULL, "recipient_type" character varying NOT NULL, "recipient_value" character varying, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workflow_schemes" ("id" SERIAL NOT NULL, "scheme_name" character varying NOT NULL, "scheme_description" character varying, CONSTRAINT "UQ_bba07c511b0002a72e521b61e2b" UNIQUE ("scheme_name"), CONSTRAINT "PK_c7ae3a291cfc9ef867a902d1428" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" SERIAL NOT NULL, "project_key" character varying NOT NULL, "project_name" character varying NOT NULL, "lead_employee_id" bigint NOT NULL, "permission_scheme_id" integer NOT NULL, "notification_scheme_id" integer NOT NULL, "workflow_scheme_id" integer NOT NULL, CONSTRAINT "UQ_c655a93948868c0af4c102745e0" UNIQUE ("project_key"), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permission_schemes" ("id" SERIAL NOT NULL, "scheme_name" character varying NOT NULL, "scheme_description" character varying, "is_default" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_f573d0d2f24e1a1d90644e7f638" UNIQUE ("scheme_name"), CONSTRAINT "PK_4e0047b7fd9ad43f1bd1139c4df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_roles" ("id" SERIAL NOT NULL, "role_name" character varying NOT NULL, "role_description" character varying, "is_default" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_d41f0ae354df16823fa00023e70" UNIQUE ("role_name"), CONSTRAINT "PK_8ac6a6996b6eaeae7b8fbb669f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."project_permissions_recipient_type_enum" AS ENUM('EMPLOYEE', 'GROUP', 'ROLE', 'REPORTER', 'ASSIGNEE')`);
        await queryRunner.query(`CREATE TABLE "project_permissions" ("id" SERIAL NOT NULL, "permission_scheme_id" integer NOT NULL, "action_key" character varying NOT NULL, "recipient_type" "public"."project_permissions_recipient_type_enum" NOT NULL, "project_role_id" integer, "specific_employee_id" bigint, "group_name" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bebd29c1039fb4f11c2727567e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_role_assignments" ("employee_id" bigint NOT NULL, "project_id" integer NOT NULL, "project_role_id" integer NOT NULL, "assigned_by_employee_id" bigint NOT NULL, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1f5d2a3e6fa219263371ae87704" PRIMARY KEY ("employee_id", "project_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1f5d2a3e6fa219263371ae8770" ON "project_role_assignments" ("employee_id", "project_id") `);
        await queryRunner.query(`CREATE TABLE "issue_assignees" ("issue_id" integer NOT NULL, "employee_id" bigint NOT NULL, CONSTRAINT "PK_7636e3e0dbb4ffd554b1c7f8086" PRIMARY KEY ("issue_id", "employee_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f9a83e6965b71c01d5fb6b21ad" ON "issue_assignees" ("issue_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_752f7b18f6778736e2120d576c" ON "issue_assignees" ("employee_id") `);
        await queryRunner.query(`CREATE TABLE "issue_watchers" ("issue_id" integer NOT NULL, "employee_id" bigint NOT NULL, CONSTRAINT "PK_7b5f821f502d28f119d605d0b6d" PRIMARY KEY ("issue_id", "employee_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_02472ad904267dfb19ce33f916" ON "issue_watchers" ("issue_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_60b89cd08e261fe7e9fcc3fb5a" ON "issue_watchers" ("employee_id") `);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_82145010051f3f2fc94671c0b35" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprint_issues" ADD CONSTRAINT "FK_8136d9e36340485a22ddfe01c75" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprint_issues" ADD CONSTRAINT "FK_492fed54de533f8641b6bc71bc3" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_statuses" ADD CONSTRAINT "FK_9a4787836ba925fb9b50d1e3073" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_scheme_mappings" ADD CONSTRAINT "FK_4590ac23a824202d8af6aae334b" FOREIGN KEY ("workflow_scheme_id") REFERENCES "workflow_schemes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_scheme_mappings" ADD CONSTRAINT "FK_c4ee3959fa2c1270f7e615b11f6" FOREIGN KEY ("issue_type_id") REFERENCES "issue_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_scheme_mappings" ADD CONSTRAINT "FK_e2362b6f481908c0112ffcf721b" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "epics" ADD CONSTRAINT "FK_dc579be47613cc4f616845d0bff" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_11f35e8296e10c229e7b68c68d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_53d9b04f3d8c1fb560cf37fad71" FOREIGN KEY ("issue_type_id") REFERENCES "issue_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_0352f4cbee4c28fd45b9ec70425" FOREIGN KEY ("current_status_id") REFERENCES "workflow_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_394a6ced54c634dfadea1618d2a" FOREIGN KEY ("reporter_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_e05271991458d0c9a69d390ecea" FOREIGN KEY ("epic_link_id") REFERENCES "epics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_links" ADD CONSTRAINT "FK_9ffae1c267c29bdf67f6d5ed3c3" FOREIGN KEY ("source_issue_id") REFERENCES "issues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_links" ADD CONSTRAINT "FK_448d9b37594d9efdf50506086ef" FOREIGN KEY ("target_issue_id") REFERENCES "issues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_comments" ADD CONSTRAINT "FK_5031938a085cb5bea6ed4eaeb53" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_comments" ADD CONSTRAINT "FK_30b9741e8c12c13be895b2a76ea" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_change_histories" ADD CONSTRAINT "FK_2fd936bfb04be33d2e6d2ce7565" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_change_histories" ADD CONSTRAINT "FK_c763d644f1cc226181ab9660a90" FOREIGN KEY ("changer_employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_e6cf236f3e8ac3fe009145bf318" FOREIGN KEY ("notification_scheme_id") REFERENCES "notification_schemes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_1e608eb6e2a4645664f0579bd16" FOREIGN KEY ("lead_employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_bdcf64ebcf08d9ca010322de98e" FOREIGN KEY ("permission_scheme_id") REFERENCES "permission_schemes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_0aeb517142499749338e608e68b" FOREIGN KEY ("notification_scheme_id") REFERENCES "notification_schemes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_318966ec1f61d6ba63ed699bc36" FOREIGN KEY ("workflow_scheme_id") REFERENCES "workflow_schemes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_permissions" ADD CONSTRAINT "FK_8da29b131cb3b488bfb8c19dc42" FOREIGN KEY ("permission_scheme_id") REFERENCES "permission_schemes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_permissions" ADD CONSTRAINT "FK_a051e70727479a301696ac99bf9" FOREIGN KEY ("project_role_id") REFERENCES "project_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_permissions" ADD CONSTRAINT "FK_1c50bb3fde65f7da38ac26e1c51" FOREIGN KEY ("specific_employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" ADD CONSTRAINT "FK_996f78c55c0fcdbb2bc4ff8fd0f" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" ADD CONSTRAINT "FK_2922f3e15002c00fffeb19b2c40" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" ADD CONSTRAINT "FK_edfdd606b217aab6b8389390b23" FOREIGN KEY ("project_role_id") REFERENCES "project_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" ADD CONSTRAINT "FK_e47c35197dcf3561fa53c61d4f7" FOREIGN KEY ("assigned_by_employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_assignees" ADD CONSTRAINT "FK_f9a83e6965b71c01d5fb6b21ad7" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "issue_assignees" ADD CONSTRAINT "FK_752f7b18f6778736e2120d576c1" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_watchers" ADD CONSTRAINT "FK_02472ad904267dfb19ce33f9160" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "issue_watchers" ADD CONSTRAINT "FK_60b89cd08e261fe7e9fcc3fb5a0" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "issue_watchers" DROP CONSTRAINT "FK_60b89cd08e261fe7e9fcc3fb5a0"`);
        await queryRunner.query(`ALTER TABLE "issue_watchers" DROP CONSTRAINT "FK_02472ad904267dfb19ce33f9160"`);
        await queryRunner.query(`ALTER TABLE "issue_assignees" DROP CONSTRAINT "FK_752f7b18f6778736e2120d576c1"`);
        await queryRunner.query(`ALTER TABLE "issue_assignees" DROP CONSTRAINT "FK_f9a83e6965b71c01d5fb6b21ad7"`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" DROP CONSTRAINT "FK_e47c35197dcf3561fa53c61d4f7"`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" DROP CONSTRAINT "FK_edfdd606b217aab6b8389390b23"`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" DROP CONSTRAINT "FK_2922f3e15002c00fffeb19b2c40"`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" DROP CONSTRAINT "FK_996f78c55c0fcdbb2bc4ff8fd0f"`);
        await queryRunner.query(`ALTER TABLE "project_permissions" DROP CONSTRAINT "FK_1c50bb3fde65f7da38ac26e1c51"`);
        await queryRunner.query(`ALTER TABLE "project_permissions" DROP CONSTRAINT "FK_a051e70727479a301696ac99bf9"`);
        await queryRunner.query(`ALTER TABLE "project_permissions" DROP CONSTRAINT "FK_8da29b131cb3b488bfb8c19dc42"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_318966ec1f61d6ba63ed699bc36"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_0aeb517142499749338e608e68b"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_bdcf64ebcf08d9ca010322de98e"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_1e608eb6e2a4645664f0579bd16"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_e6cf236f3e8ac3fe009145bf318"`);
        await queryRunner.query(`ALTER TABLE "issue_change_histories" DROP CONSTRAINT "FK_c763d644f1cc226181ab9660a90"`);
        await queryRunner.query(`ALTER TABLE "issue_change_histories" DROP CONSTRAINT "FK_2fd936bfb04be33d2e6d2ce7565"`);
        await queryRunner.query(`ALTER TABLE "issue_comments" DROP CONSTRAINT "FK_30b9741e8c12c13be895b2a76ea"`);
        await queryRunner.query(`ALTER TABLE "issue_comments" DROP CONSTRAINT "FK_5031938a085cb5bea6ed4eaeb53"`);
        await queryRunner.query(`ALTER TABLE "issue_links" DROP CONSTRAINT "FK_448d9b37594d9efdf50506086ef"`);
        await queryRunner.query(`ALTER TABLE "issue_links" DROP CONSTRAINT "FK_9ffae1c267c29bdf67f6d5ed3c3"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_e05271991458d0c9a69d390ecea"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_394a6ced54c634dfadea1618d2a"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_0352f4cbee4c28fd45b9ec70425"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_53d9b04f3d8c1fb560cf37fad71"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_11f35e8296e10c229e7b68c68d4"`);
        await queryRunner.query(`ALTER TABLE "epics" DROP CONSTRAINT "FK_dc579be47613cc4f616845d0bff"`);
        await queryRunner.query(`ALTER TABLE "workflow_scheme_mappings" DROP CONSTRAINT "FK_e2362b6f481908c0112ffcf721b"`);
        await queryRunner.query(`ALTER TABLE "workflow_scheme_mappings" DROP CONSTRAINT "FK_c4ee3959fa2c1270f7e615b11f6"`);
        await queryRunner.query(`ALTER TABLE "workflow_scheme_mappings" DROP CONSTRAINT "FK_4590ac23a824202d8af6aae334b"`);
        await queryRunner.query(`ALTER TABLE "workflow_statuses" DROP CONSTRAINT "FK_9a4787836ba925fb9b50d1e3073"`);
        await queryRunner.query(`ALTER TABLE "sprint_issues" DROP CONSTRAINT "FK_492fed54de533f8641b6bc71bc3"`);
        await queryRunner.query(`ALTER TABLE "sprint_issues" DROP CONSTRAINT "FK_8136d9e36340485a22ddfe01c75"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_82145010051f3f2fc94671c0b35"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60b89cd08e261fe7e9fcc3fb5a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02472ad904267dfb19ce33f916"`);
        await queryRunner.query(`DROP TABLE "issue_watchers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_752f7b18f6778736e2120d576c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9a83e6965b71c01d5fb6b21ad"`);
        await queryRunner.query(`DROP TABLE "issue_assignees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f5d2a3e6fa219263371ae8770"`);
        await queryRunner.query(`DROP TABLE "project_role_assignments"`);
        await queryRunner.query(`DROP TABLE "project_permissions"`);
        await queryRunner.query(`DROP TYPE "public"."project_permissions_recipient_type_enum"`);
        await queryRunner.query(`DROP TABLE "project_roles"`);
        await queryRunner.query(`DROP TABLE "permission_schemes"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TABLE "workflow_schemes"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "notification_schemes"`);
        await queryRunner.query(`DROP TABLE "issue_change_histories"`);
        await queryRunner.query(`DROP TABLE "issue_comments"`);
        await queryRunner.query(`DROP TABLE "issue_links"`);
        await queryRunner.query(`DROP TABLE "issues"`);
        await queryRunner.query(`DROP TABLE "epics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ff2c1c4c5668bda6cadc4eca8"`);
        await queryRunner.query(`DROP TABLE "workflow_scheme_mappings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38b7a83f7dad794d535bb1c82d"`);
        await queryRunner.query(`DROP TABLE "workflow_statuses"`);
        await queryRunner.query(`DROP TABLE "workflows"`);
        await queryRunner.query(`DROP TABLE "issue_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14ea8d57167fbfb24774c401b4"`);
        await queryRunner.query(`DROP TABLE "sprint_issues"`);
        await queryRunner.query(`DROP TABLE "sprints"`);
    }

}
