import { MigrationInterface, QueryRunner } from "typeorm";

export class Auto1765467235716 implements MigrationInterface {
    name = 'Auto1765467235716'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_d62835db8c0aec1d18a5a927549"`);
        await queryRunner.query(`ALTER TABLE "employee_devices" DROP CONSTRAINT "FK_employee_devices_employee"`);
        await queryRunner.query(`ALTER TABLE "employee_devices" DROP CONSTRAINT "FK_employee_devices_registered_by"`);
        await queryRunner.query(`ALTER TABLE "attendance_challenges" DROP CONSTRAINT "FK_attendance_challenges_employee"`);
        await queryRunner.query(`ALTER TABLE "salary_settings" DROP CONSTRAINT "fk_salary_settings_role"`);
        await queryRunner.query(`ALTER TABLE "salary_settings" DROP CONSTRAINT "fk_salary_settings_employee"`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP CONSTRAINT "fk_overtime_employee"`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP CONSTRAINT "fk_overtime_approver"`);
        await queryRunner.query(`ALTER TABLE "late_early_request" DROP CONSTRAINT "fk_late_early_employee"`);
        await queryRunner.query(`ALTER TABLE "late_early_request" DROP CONSTRAINT "fk_late_early_approver"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employee_device_unique"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_attendance_challenges_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_attendance_challenges_employee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_asset_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_asset_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_asset_current_holder"`);
        await queryRunner.query(`ALTER TABLE "salary_settings" DROP CONSTRAINT "chk_salary_settings_one_target"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "check_in_longitude"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "check_out_longitude"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "check_in_latitude"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "check_out_latitude"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "device_id"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "gps_accuracy"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "email_verification_token"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "email_verification_token_created_at"`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "check_in_setting" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "check_out_setting" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "two_factor_enabled" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`COMMENT ON COLUMN "employee"."two_factor_enabled" IS 'Enable two-factor authentication'`);
        await queryRunner.query(`ALTER TABLE "attendance" ALTER COLUMN "is_verified" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "employee_salary"."insurance" IS 'Bảo hiểm'`);
        await queryRunner.query(`COMMENT ON COLUMN "employee_salary"."overtime_salary" IS 'Lương OT'`);
        await queryRunner.query(`COMMENT ON COLUMN "employee_salary"."overtime_hours" IS 'Số giờ OT'`);
        await queryRunner.query(`COMMENT ON COLUMN "employee_salary"."work_days" IS 'Số ngày làm việc'`);
        await queryRunner.query(`COMMENT ON COLUMN "employee_salary"."approved_leave_days" IS 'Số ngày nghỉ có phép (đã duyệt)'`);
        await queryRunner.query(`ALTER TABLE "employee" ALTER COLUMN "annual_leave_limit" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ALTER COLUMN "remaining_leave_days" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_devices" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."employee_devices_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED')`);
        await queryRunner.query(`ALTER TABLE "employee_devices" ADD "status" "public"."employee_devices_status_enum" NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "employee_devices" ALTER COLUMN "is_primary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendance_challenges" ALTER COLUMN "is_used" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."standard_check_in_time" IS 'Giờ check-in chuẩn (HH:mm:ss)'`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."standard_check_out_time" IS 'Giờ check-out chuẩn (HH:mm:ss)'`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "monday" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."monday" IS 'Thứ 2'`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "tuesday" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."tuesday" IS 'Thứ 3'`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "wednesday" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."wednesday" IS 'Thứ 4'`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "thursday" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."thursday" IS 'Thứ 5'`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "friday" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."friday" IS 'Thứ 6'`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "saturday" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."saturday" IS 'Thứ 7'`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "sunday" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."sunday" IS 'Chủ nhật'`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "standard_work_hours_per_day" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."standard_work_hours_per_day" IS 'Số giờ làm việc chuẩn mỗi ngày'`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "standard_work_hours_per_day" SET DEFAULT '8'`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "late_tolerance_minutes" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."late_tolerance_minutes" IS 'Thời gian cho phép đi muộn (phút)'`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "early_leave_tolerance_minutes" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."early_leave_tolerance_minutes" IS 'Thời gian cho phép về sớm (phút)'`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."role_id" IS 'Role ID - nếu null thì là setting cho employee cụ thể'`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."employee_id" IS 'Employee ID - nếu null thì là setting cho role'`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."base_salary" IS 'Lương cơ bản (VND)'`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "allowance" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."allowance" IS 'Phụ cấp (VND)'`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "insurance_rate" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."insurance_rate" IS 'Tỷ lệ bảo hiểm (%)'`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "insurance_rate" SET DEFAULT '10.5'`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "salary_coefficient" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."salary_coefficient" IS 'Hệ số lương'`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "salary_coefficient" SET DEFAULT '1'`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."hourly_rate" IS 'Lương theo giờ (VND/giờ) - tự động tính từ base_salary'`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "overtime_rate" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."overtime_rate" IS 'Hệ số lương làm thêm giờ'`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "overtime_rate" SET DEFAULT '1.5'`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "holiday_rate" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."holiday_rate" IS 'Hệ số lương ngày nghỉ (nếu làm việc)'`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "holiday_rate" SET DEFAULT '2'`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."date" IS 'Ngày làm thêm giờ'`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."start_time" IS 'Giờ bắt đầu OT (HH:mm:ss)'`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."end_time" IS 'Giờ kết thúc OT (HH:mm:ss)'`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."hours" IS 'Số giờ OT'`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."reason" IS 'Lý do làm thêm giờ'`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."overtime_request_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD "status" "public"."overtime_request_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."approved_by" IS 'Người duyệt'`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."approved_at" IS 'Thời gian duyệt'`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."approval_note" IS 'Ghi chú từ người duyệt'`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."date" IS 'Ngày đi muộn/về sớm'`);
        await queryRunner.query(`ALTER TABLE "late_early_request" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."late_early_request_type_enum" AS ENUM('LATE', 'EARLY')`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ADD "type" "public"."late_early_request_type_enum" NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."type" IS 'Loại: LATE hoặc EARLY'`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."actual_time" IS 'Giờ thực tế (nếu đi muộn thì là giờ check-in, nếu về sớm thì là giờ check-out)'`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."minutes" IS 'Số phút muộn/sớm'`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."reason" IS 'Lý do'`);
        await queryRunner.query(`ALTER TABLE "late_early_request" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."late_early_request_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ADD "status" "public"."late_early_request_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."approved_by" IS 'Người duyệt'`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."approved_at" IS 'Thời gian duyệt'`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."approval_note" IS 'Ghi chú từ người duyệt'`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_37689c8b97d053209a3df8b33f" ON "employee_devices" ("employee_id", "device_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c97acd2690919ebfd0d611ac2e" ON "attendance_challenges" ("token") `);
        await queryRunner.query(`ALTER TABLE "workflow_scheme_mappings" ADD CONSTRAINT "FK_e2362b6f481908c0112ffcf721b" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_devices" ADD CONSTRAINT "FK_d5d3a44de6ea33fd232a7da7748" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_devices" ADD CONSTRAINT "FK_aef9f84ad30a7498fef3c3a6072" FOREIGN KEY ("registered_by") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_challenges" ADD CONSTRAINT "FK_fb566b7a68972562f936d78d1c7" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ADD CONSTRAINT "FK_98b6b8df74fb14ff04085f2a8a8" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ADD CONSTRAINT "FK_20b87bba1b5b1d45116680d11a4" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD CONSTRAINT "FK_cc55b2f56774c09e8290a0823fa" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD CONSTRAINT "FK_bc788329bde5aee398cc24bf254" FOREIGN KEY ("approved_by") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ADD CONSTRAINT "FK_47601bebe4d909cfbbe8654dd26" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ADD CONSTRAINT "FK_dfe7175c51413b4f16dcd8d37d8" FOREIGN KEY ("approved_by") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "late_early_request" DROP CONSTRAINT "FK_dfe7175c51413b4f16dcd8d37d8"`);
        await queryRunner.query(`ALTER TABLE "late_early_request" DROP CONSTRAINT "FK_47601bebe4d909cfbbe8654dd26"`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP CONSTRAINT "FK_bc788329bde5aee398cc24bf254"`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP CONSTRAINT "FK_cc55b2f56774c09e8290a0823fa"`);
        await queryRunner.query(`ALTER TABLE "salary_settings" DROP CONSTRAINT "FK_20b87bba1b5b1d45116680d11a4"`);
        await queryRunner.query(`ALTER TABLE "salary_settings" DROP CONSTRAINT "FK_98b6b8df74fb14ff04085f2a8a8"`);
        await queryRunner.query(`ALTER TABLE "attendance_challenges" DROP CONSTRAINT "FK_fb566b7a68972562f936d78d1c7"`);
        await queryRunner.query(`ALTER TABLE "employee_devices" DROP CONSTRAINT "FK_aef9f84ad30a7498fef3c3a6072"`);
        await queryRunner.query(`ALTER TABLE "employee_devices" DROP CONSTRAINT "FK_d5d3a44de6ea33fd232a7da7748"`);
        await queryRunner.query(`ALTER TABLE "workflow_scheme_mappings" DROP CONSTRAINT "FK_e2362b6f481908c0112ffcf721b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c97acd2690919ebfd0d611ac2e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37689c8b97d053209a3df8b33f"`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."approval_note" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."approved_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."approved_by" IS NULL`);
        await queryRunner.query(`ALTER TABLE "late_early_request" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."late_early_request_status_enum"`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ADD "status" character varying(20) DEFAULT 'PENDING'`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."reason" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."minutes" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."actual_time" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."type" IS 'Loại: LATE hoặc EARLY'`);
        await queryRunner.query(`ALTER TABLE "late_early_request" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."late_early_request_type_enum"`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ADD "type" character varying(10) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "late_early_request"."date" IS NULL`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."approval_note" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."approved_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."approved_by" IS NULL`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."overtime_request_status_enum"`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD "status" character varying(20) DEFAULT 'PENDING'`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."reason" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."hours" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."end_time" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."start_time" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "overtime_request"."date" IS NULL`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "holiday_rate" SET DEFAULT 2.0`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."holiday_rate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "holiday_rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "overtime_rate" SET DEFAULT 1.5`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."overtime_rate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "overtime_rate" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."hourly_rate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "salary_coefficient" SET DEFAULT 1.0`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."salary_coefficient" IS NULL`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "salary_coefficient" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "insurance_rate" SET DEFAULT 10.5`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."insurance_rate" IS NULL`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "insurance_rate" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."allowance" IS NULL`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ALTER COLUMN "allowance" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."base_salary" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."employee_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "salary_settings"."role_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."early_leave_tolerance_minutes" IS NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "early_leave_tolerance_minutes" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."late_tolerance_minutes" IS NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "late_tolerance_minutes" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "standard_work_hours_per_day" SET DEFAULT 8.0`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."standard_work_hours_per_day" IS NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "standard_work_hours_per_day" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."sunday" IS NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "sunday" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."saturday" IS NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "saturday" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."friday" IS NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "friday" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."thursday" IS NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "thursday" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."wednesday" IS NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "wednesday" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."tuesday" IS NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "tuesday" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."monday" IS NULL`);
        await queryRunner.query(`ALTER TABLE "work_schedule_settings" ALTER COLUMN "monday" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."standard_check_out_time" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "work_schedule_settings"."standard_check_in_time" IS NULL`);
        await queryRunner.query(`ALTER TABLE "attendance_challenges" ALTER COLUMN "is_used" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_devices" ALTER COLUMN "is_primary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee_devices" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."employee_devices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employee_devices" ADD "status" character varying(20) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "employee" ALTER COLUMN "remaining_leave_days" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ALTER COLUMN "annual_leave_limit" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "employee_salary"."approved_leave_days" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "employee_salary"."work_days" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "employee_salary"."overtime_hours" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "employee_salary"."overtime_salary" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "employee_salary"."insurance" IS NULL`);
        await queryRunner.query(`ALTER TABLE "attendance" ALTER COLUMN "is_verified" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "employee"."two_factor_enabled" IS 'Enable two-factor authentication'`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "two_factor_enabled"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "check_out_setting"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP COLUMN "check_in_setting"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "email_verification_token_created_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "department_id" integer`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "email_verification_token" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "ip_address" character varying(45)`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "gps_accuracy" integer`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "device_id" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "check_out_latitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "check_in_latitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "user_agent" text`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "check_out_longitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD "check_in_longitude" numeric(10,7)`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ADD CONSTRAINT "chk_salary_settings_one_target" CHECK ((((role_id IS NOT NULL) AND (employee_id IS NULL)) OR ((role_id IS NULL) AND (employee_id IS NOT NULL))))`);
        await queryRunner.query(`CREATE INDEX "IDX_asset_current_holder" ON "asset" ("current_holder_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_asset_status" ON "asset" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_asset_category_id" ON "asset" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_attendance_challenges_employee" ON "attendance_challenges" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_attendance_challenges_token" ON "attendance_challenges" ("token") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_employee_device_unique" ON "employee_devices" ("employee_id", "device_id") `);
        await queryRunner.query(`ALTER TABLE "late_early_request" ADD CONSTRAINT "fk_late_early_approver" FOREIGN KEY ("approved_by") REFERENCES "employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ADD CONSTRAINT "fk_late_early_employee" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD CONSTRAINT "fk_overtime_approver" FOREIGN KEY ("approved_by") REFERENCES "employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD CONSTRAINT "fk_overtime_employee" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ADD CONSTRAINT "fk_salary_settings_employee" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ADD CONSTRAINT "fk_salary_settings_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_challenges" ADD CONSTRAINT "FK_attendance_challenges_employee" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_devices" ADD CONSTRAINT "FK_employee_devices_registered_by" FOREIGN KEY ("registered_by") REFERENCES "employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_devices" ADD CONSTRAINT "FK_employee_devices_employee" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_d62835db8c0aec1d18a5a927549" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
