import { MigrationInterface, QueryRunner } from "typeorm";

export class Auto1765424024384 implements MigrationInterface {
    name = 'Auto1765424024384'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "code" character varying(150) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f6d54f95c31b73fb1bdd8e91d0c" UNIQUE ("code"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employee_roles" ("employee_id" integer NOT NULL, "role_id" integer NOT NULL, CONSTRAINT "PK_8bf7f2fbc9039751cd34d9f9606" PRIMARY KEY ("employee_id", "role_id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" SERIAL NOT NULL, "employee_id" integer NOT NULL, "token_hash" text NOT NULL, "expires_at" TIMESTAMP NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "employee_id" integer, "action" character varying(255), "resource_type" character varying(100), "resource_id" character varying(100), "ip" character varying(45), "user_agent" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workflows" ("id" SERIAL NOT NULL, "workflow_name" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_29684cccd5d9bbefb20cb92466e" UNIQUE ("workflow_name"), CONSTRAINT "PK_5b5757cc1cd86268019fef52e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workflow_schemes" ("id" SERIAL NOT NULL, "scheme_name" character varying NOT NULL, "scheme_description" character varying, CONSTRAINT "UQ_bba07c511b0002a72e521b61e2b" UNIQUE ("scheme_name"), CONSTRAINT "PK_c7ae3a291cfc9ef867a902d1428" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workflow_statuses" ("id" SERIAL NOT NULL, "workflow_id" integer NOT NULL, "order_index" integer NOT NULL DEFAULT '0', "status_name" character varying NOT NULL, "status_category" character varying, "is_initial_status" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_5933af9b773c575a905467543f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_38b7a83f7dad794d535bb1c82d" ON "workflow_statuses" ("workflow_id", "status_name") `);
        await queryRunner.query(`CREATE TABLE "workflow_scheme_mappings" ("workflow_scheme_id" integer NOT NULL, "issue_type_id" integer NOT NULL, "workflow_id" integer NOT NULL, CONSTRAINT "PK_3ff2c1c4c5668bda6cadc4eca8d" PRIMARY KEY ("workflow_scheme_id", "issue_type_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3ff2c1c4c5668bda6cadc4eca8" ON "workflow_scheme_mappings" ("workflow_scheme_id", "issue_type_id") `);
        await queryRunner.query(`CREATE TABLE "issue_types" ("id" SERIAL NOT NULL, "type_name" character varying NOT NULL, CONSTRAINT "UQ_c627a437a238428ebd2c9f0b4d7" UNIQUE ("type_name"), CONSTRAINT "PK_24907560935389ac8139cee3f85" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "epics" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "epic_name" character varying NOT NULL, "goal" text, "status" character varying, "start_date" date, "due_date" date, CONSTRAINT "PK_aa782b1b14b73c7a38f04b71e3f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "issues" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "issue_type_id" integer NOT NULL, "order_index" integer NOT NULL DEFAULT '0', "summary" character varying NOT NULL, "issue_code" character varying NOT NULL, "description" text, "current_status_id" integer NOT NULL, "reporter_id" integer NOT NULL, "epic_link_id" integer, "story_points" integer, "original_estimate_seconds" integer, "time_spent_seconds" integer, "resolution" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9d8ecbbeff46229c700f0449257" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "issue_links" ("id" SERIAL NOT NULL, "source_issue_id" integer NOT NULL, "target_issue_id" integer NOT NULL, "link_type" character varying NOT NULL, CONSTRAINT "PK_92c961bad3a83cebd040a61d87f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "issue_comments" ("id" SERIAL NOT NULL, "issue_id" integer NOT NULL, "employee_id" integer NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c650a2d6817045a0c8ce74f09f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "issue_change_histories" ("id" SERIAL NOT NULL, "issue_id" integer NOT NULL, "changer_employee_id" integer NOT NULL, "change_date" TIMESTAMP NOT NULL, "field_name" character varying NOT NULL, "old_value" character varying, "new_value" character varying, CONSTRAINT "PK_4a3b52726e1bcdf4a21ec5270f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" SERIAL NOT NULL, "project_key" character varying NOT NULL, "project_name" character varying NOT NULL, "lead_employee_id" integer NOT NULL, "permission_scheme_id" integer NOT NULL, "notification_scheme_id" integer NOT NULL, "workflow_scheme_id" integer NOT NULL, CONSTRAINT "UQ_c655a93948868c0af4c102745e0" UNIQUE ("project_key"), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" SERIAL NOT NULL, "name" character varying(150) NOT NULL, "parent_id" integer, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "positions" ("id" SERIAL NOT NULL, "title" character varying(150) NOT NULL, "level" smallint, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_17e4e62ccd5749b289ae3fae6f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employee_positions" ("id" SERIAL NOT NULL, "employee_id" integer NOT NULL, "department_id" integer, "position_id" integer, "start_date" date NOT NULL, "end_date" date, "contract_file" text, "is_current" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8544f049d46ad635c8cb2b9fc0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" SERIAL NOT NULL, "employee_id" integer NOT NULL, "date" date NOT NULL, "check_in" TIMESTAMP WITH TIME ZONE, "check_out" TIMESTAMP WITH TIME ZONE, "work_hours" numeric(6,2), "late_minutes" integer DEFAULT '0', "early_leave_minutes" integer DEFAULT '0', "note" text, "check_in_photo_url" text, "check_out_photo_url" text, "is_verified" boolean NOT NULL DEFAULT false, "verification_notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employee_salary" ("id" SERIAL NOT NULL, "employee_id" integer NOT NULL, "month" date NOT NULL, "base_salary" numeric(14,2), "work_hours" numeric(8,2), "bonus" numeric(12,2) DEFAULT '0', "allowance" numeric(12,2) DEFAULT '0', "insurance" numeric(12,2) DEFAULT '0', "overtime_salary" numeric(12,2) DEFAULT '0', "overtime_hours" numeric(8,2) DEFAULT '0', "work_days" numeric(5,2) DEFAULT '0', "approved_leave_days" numeric(5,2) DEFAULT '0', "deduction" numeric(12,2) DEFAULT '0', "total_salary" numeric(14,2), "status" "public"."employee_salary_status_enum" NOT NULL DEFAULT 'PENDING', "pay_date" date, "payment_method" "public"."employee_salary_payment_method_enum", "pay_slip_file" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b7f7a2169fecb7b83d8e7b05dd7" PRIMARY KEY ("id")); COMMENT ON COLUMN "employee_salary"."insurance" IS 'Bảo hiểm'; COMMENT ON COLUMN "employee_salary"."overtime_salary" IS 'Lương OT'; COMMENT ON COLUMN "employee_salary"."overtime_hours" IS 'Số giờ OT'; COMMENT ON COLUMN "employee_salary"."work_days" IS 'Số ngày làm việc'; COMMENT ON COLUMN "employee_salary"."approved_leave_days" IS 'Số ngày nghỉ có phép (đã duyệt)'`);
        await queryRunner.query(`CREATE TABLE "leave_request" ("id" SERIAL NOT NULL, "employee_id" integer NOT NULL, "type" "public"."leave_request_type_enum" NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "total_days" numeric(5,2), "reason" text, "status" "public"."leave_request_status_enum" NOT NULL DEFAULT 'PENDING', "approved_by" integer, "approved_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6f6ed3822203a4e10a5753368db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "files" ("id" SERIAL NOT NULL, "employee_id" integer, "file_name" character varying(255) NOT NULL, "file_type" character varying(50), "file_url" text NOT NULL, "category" "public"."files_category_enum", "uploaded_by" integer, "uploaded_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employee" ("id" SERIAL NOT NULL, "employee_code" character varying(100) NOT NULL, "username" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "password_hash" text, "full_name" character varying(255) NOT NULL, "first_name" character varying(100), "last_name" character varying(100), "gender" "public"."employee_gender_enum", "dob" date, "national_id" character varying(20), "address" text, "phone" character varying(30), "department" character varying(255), "position" character varying(255), "avatar_url" text, "timezone" character varying(100), "role" "public"."employee_role_enum", "status" "public"."employee_status_enum" NOT NULL DEFAULT 'ACTIVE', "is_verified" boolean NOT NULL DEFAULT false, "failed_login_count" integer NOT NULL DEFAULT '0', "locked_until" TIMESTAMP, "two_factor_enabled" boolean NOT NULL DEFAULT false, "last_login" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "qr_code_url" text, "face_image_url" text, "face_embedding" text, "face_registered_at" TIMESTAMP, "annual_leave_limit" integer NOT NULL DEFAULT '12', "remaining_leave_days" integer NOT NULL DEFAULT '12', "email_verified_at" TIMESTAMP, CONSTRAINT "UQ_389fe2fe09430efb8eabc4e1b6e" UNIQUE ("username"), CONSTRAINT "UQ_817d1d427138772d47eca048855" UNIQUE ("email"), CONSTRAINT "PK_3c2bc72f03fd5abbbc5ac169498" PRIMARY KEY ("id")); COMMENT ON COLUMN "employee"."two_factor_enabled" IS 'Enable two-factor authentication'; COMMENT ON COLUMN "employee"."annual_leave_limit" IS 'Annual leave limit in days per year'; COMMENT ON COLUMN "employee"."remaining_leave_days" IS 'Remaining annual leave days for current year'; COMMENT ON COLUMN "employee"."email_verified_at" IS 'Email verified timestamp'`);
        await queryRunner.query(`CREATE TABLE "notification_schemes" ("id" SERIAL NOT NULL, "scheme_name" character varying NOT NULL, "scheme_description" character varying, CONSTRAINT "UQ_da94bdf01d2a801f3a34692758a" UNIQUE ("scheme_name"), CONSTRAINT "PK_160024a02eb60517fe964838c12" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_notifications" ("id" SERIAL NOT NULL, "notification_scheme_id" integer NOT NULL, "event_name" character varying NOT NULL, "recipient_type" character varying NOT NULL, "recipient_value" character varying, CONSTRAINT "PK_153224d519cae0aa975fa53687d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprints" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "sprint_name" character varying NOT NULL, "goal" text, "start_date" TIMESTAMP, "end_date" TIMESTAMP, "duration_days" integer, "status" character varying NOT NULL, CONSTRAINT "PK_6800aa2e0f508561812c4b9afb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sprint_issues" ("sprint_id" integer NOT NULL, "issue_id" integer NOT NULL, "rank_order" integer, CONSTRAINT "PK_14ea8d57167fbfb24774c401b48" PRIMARY KEY ("sprint_id", "issue_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_14ea8d57167fbfb24774c401b4" ON "sprint_issues" ("sprint_id", "issue_id") `);
        await queryRunner.query(`CREATE TABLE "permission_schemes" ("id" SERIAL NOT NULL, "scheme_name" character varying NOT NULL, "scheme_description" character varying, "is_default" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_f573d0d2f24e1a1d90644e7f638" UNIQUE ("scheme_name"), CONSTRAINT "PK_4e0047b7fd9ad43f1bd1139c4df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_roles" ("id" SERIAL NOT NULL, "role_name" character varying NOT NULL, "role_description" character varying, "is_default" boolean NOT NULL DEFAULT false, "permission_scheme_id" integer, "created_at" TIMESTAMP DEFAULT now(), CONSTRAINT "UQ_d41f0ae354df16823fa00023e70" UNIQUE ("role_name"), CONSTRAINT "PK_8ac6a6996b6eaeae7b8fbb669f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_permissions" ("id" SERIAL NOT NULL, "permission_scheme_id" integer NOT NULL, "action_key" character varying NOT NULL, "recipient_type" "public"."project_permissions_recipient_type_enum" NOT NULL, "project_role_id" integer, "specific_employee_id" integer, "group_name" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bebd29c1039fb4f11c2727567e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_role_assignments" ("employee_id" integer NOT NULL, "project_id" integer NOT NULL, "project_role_id" integer NOT NULL, "assigned_by_employee_id" integer NOT NULL, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1f5d2a3e6fa219263371ae87704" PRIMARY KEY ("employee_id", "project_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1f5d2a3e6fa219263371ae8770" ON "project_role_assignments" ("employee_id", "project_id") `);
        await queryRunner.query(`CREATE TABLE "reports" ("id" SERIAL NOT NULL, "type" character varying(50) NOT NULL, "title" character varying(255), "file_url" text, "generated_by" integer, "params" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employee_devices" ("id" SERIAL NOT NULL, "employee_id" integer NOT NULL, "device_id" character varying(255) NOT NULL, "device_name" character varying(100), "device_type" character varying(50), "os" character varying(100), "browser" character varying(100), "screen_resolution" character varying(50), "timezone" character varying(50), "language" character varying(20), "user_agent" text, "status" "public"."employee_devices_status_enum" NOT NULL DEFAULT 'ACTIVE', "last_used_at" TIMESTAMP WITH TIME ZONE, "last_ip_address" character varying(45), "is_primary" boolean NOT NULL DEFAULT false, "registered_by" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a612188472c3f03e391bfbf285d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_37689c8b97d053209a3df8b33f" ON "employee_devices" ("employee_id", "device_id") `);
        await queryRunner.query(`CREATE TABLE "attendance_challenges" ("id" SERIAL NOT NULL, "employee_id" integer NOT NULL, "token" character varying(255) NOT NULL, "action_type" character varying(20) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "is_used" boolean NOT NULL DEFAULT false, "used_at" TIMESTAMP WITH TIME ZONE, "expected_device_id" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_c97acd2690919ebfd0d611ac2eb" UNIQUE ("token"), CONSTRAINT "PK_3e12a5625b0c93316e2cc6bc468" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c97acd2690919ebfd0d611ac2e" ON "attendance_challenges" ("token") `);
        await queryRunner.query(`CREATE TABLE "work_schedule_settings" ("id" SERIAL NOT NULL, "standard_check_in_time" TIME NOT NULL, "standard_check_out_time" TIME NOT NULL, "monday" boolean NOT NULL DEFAULT true, "tuesday" boolean NOT NULL DEFAULT true, "wednesday" boolean NOT NULL DEFAULT true, "thursday" boolean NOT NULL DEFAULT true, "friday" boolean NOT NULL DEFAULT true, "saturday" boolean NOT NULL DEFAULT false, "sunday" boolean NOT NULL DEFAULT false, "standard_work_hours_per_day" numeric(4,2) NOT NULL DEFAULT '8', "late_tolerance_minutes" integer NOT NULL DEFAULT '15', "early_leave_tolerance_minutes" integer NOT NULL DEFAULT '15', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6c8db54bf2db87c250672948e7e" PRIMARY KEY ("id")); COMMENT ON COLUMN "work_schedule_settings"."standard_check_in_time" IS 'Giờ check-in chuẩn (HH:mm:ss)'; COMMENT ON COLUMN "work_schedule_settings"."standard_check_out_time" IS 'Giờ check-out chuẩn (HH:mm:ss)'; COMMENT ON COLUMN "work_schedule_settings"."monday" IS 'Thứ 2'; COMMENT ON COLUMN "work_schedule_settings"."tuesday" IS 'Thứ 3'; COMMENT ON COLUMN "work_schedule_settings"."wednesday" IS 'Thứ 4'; COMMENT ON COLUMN "work_schedule_settings"."thursday" IS 'Thứ 5'; COMMENT ON COLUMN "work_schedule_settings"."friday" IS 'Thứ 6'; COMMENT ON COLUMN "work_schedule_settings"."saturday" IS 'Thứ 7'; COMMENT ON COLUMN "work_schedule_settings"."sunday" IS 'Chủ nhật'; COMMENT ON COLUMN "work_schedule_settings"."standard_work_hours_per_day" IS 'Số giờ làm việc chuẩn mỗi ngày'; COMMENT ON COLUMN "work_schedule_settings"."late_tolerance_minutes" IS 'Thời gian cho phép đi muộn (phút)'; COMMENT ON COLUMN "work_schedule_settings"."early_leave_tolerance_minutes" IS 'Thời gian cho phép về sớm (phút)'`);
        await queryRunner.query(`CREATE TABLE "salary_settings" ("id" SERIAL NOT NULL, "role_id" integer, "employee_id" integer, "base_salary" numeric(14,2) NOT NULL, "allowance" numeric(12,2) NOT NULL DEFAULT '0', "insurance_rate" numeric(5,2) NOT NULL DEFAULT '10.5', "salary_coefficient" numeric(5,2) NOT NULL DEFAULT '1', "hourly_rate" numeric(12,2), "overtime_rate" numeric(5,2) NOT NULL DEFAULT '1.5', "holiday_rate" numeric(5,2) NOT NULL DEFAULT '2', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ef0271ad531d6459800c64e98d3" PRIMARY KEY ("id")); COMMENT ON COLUMN "salary_settings"."role_id" IS 'Role ID - nếu null thì là setting cho employee cụ thể'; COMMENT ON COLUMN "salary_settings"."employee_id" IS 'Employee ID - nếu null thì là setting cho role'; COMMENT ON COLUMN "salary_settings"."base_salary" IS 'Lương cơ bản (VND)'; COMMENT ON COLUMN "salary_settings"."allowance" IS 'Phụ cấp (VND)'; COMMENT ON COLUMN "salary_settings"."insurance_rate" IS 'Tỷ lệ bảo hiểm (%)'; COMMENT ON COLUMN "salary_settings"."salary_coefficient" IS 'Hệ số lương'; COMMENT ON COLUMN "salary_settings"."hourly_rate" IS 'Lương theo giờ (VND/giờ) - tự động tính từ base_salary'; COMMENT ON COLUMN "salary_settings"."overtime_rate" IS 'Hệ số lương làm thêm giờ'; COMMENT ON COLUMN "salary_settings"."holiday_rate" IS 'Hệ số lương ngày nghỉ (nếu làm việc)'`);
        await queryRunner.query(`CREATE TYPE "public"."overtime_request_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "overtime_request" ("id" SERIAL NOT NULL, "employee_id" integer NOT NULL, "date" date NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "hours" numeric(6,2), "reason" text, "status" "public"."overtime_request_status_enum" NOT NULL DEFAULT 'PENDING', "approved_by" integer, "approved_at" TIMESTAMP WITH TIME ZONE, "approval_note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ed27e3ef1c553fba41969ffeee5" PRIMARY KEY ("id")); COMMENT ON COLUMN "overtime_request"."date" IS 'Ngày làm thêm giờ'; COMMENT ON COLUMN "overtime_request"."start_time" IS 'Giờ bắt đầu OT (HH:mm:ss)'; COMMENT ON COLUMN "overtime_request"."end_time" IS 'Giờ kết thúc OT (HH:mm:ss)'; COMMENT ON COLUMN "overtime_request"."hours" IS 'Số giờ OT'; COMMENT ON COLUMN "overtime_request"."reason" IS 'Lý do làm thêm giờ'; COMMENT ON COLUMN "overtime_request"."approved_by" IS 'Người duyệt'; COMMENT ON COLUMN "overtime_request"."approved_at" IS 'Thời gian duyệt'; COMMENT ON COLUMN "overtime_request"."approval_note" IS 'Ghi chú từ người duyệt'`);
        await queryRunner.query(`CREATE TYPE "public"."late_early_request_type_enum" AS ENUM('LATE', 'EARLY')`);
        await queryRunner.query(`CREATE TYPE "public"."late_early_request_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "late_early_request" ("id" SERIAL NOT NULL, "employee_id" integer NOT NULL, "date" date NOT NULL, "type" "public"."late_early_request_type_enum" NOT NULL, "actual_time" TIME, "minutes" integer, "reason" text, "status" "public"."late_early_request_status_enum" NOT NULL DEFAULT 'PENDING', "approved_by" integer, "approved_at" TIMESTAMP WITH TIME ZONE, "approval_note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cbd00441e4bcbad7a9430c14c68" PRIMARY KEY ("id")); COMMENT ON COLUMN "late_early_request"."date" IS 'Ngày đi muộn/về sớm'; COMMENT ON COLUMN "late_early_request"."type" IS 'Loại: LATE hoặc EARLY'; COMMENT ON COLUMN "late_early_request"."actual_time" IS 'Giờ thực tế (nếu đi muộn thì là giờ check-in, nếu về sớm thì là giờ check-out)'; COMMENT ON COLUMN "late_early_request"."minutes" IS 'Số phút muộn/sớm'; COMMENT ON COLUMN "late_early_request"."reason" IS 'Lý do'; COMMENT ON COLUMN "late_early_request"."approved_by" IS 'Người duyệt'; COMMENT ON COLUMN "late_early_request"."approved_at" IS 'Thời gian duyệt'; COMMENT ON COLUMN "late_early_request"."approval_note" IS 'Ghi chú từ người duyệt'`);
        await queryRunner.query(`CREATE TABLE "category" ("id" SERIAL NOT NULL, "category_code" character varying(50) NOT NULL, "category_name" character varying(255) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b86357ea34c7b4e7338bfe536dd" UNIQUE ("category_code"), CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."asset_status_enum" AS ENUM('NEW', 'IN_USE', 'UNDER_REPAIR', 'UNDER_MAINTENANCE', 'BROKEN', 'LIQUIDATED')`);
        await queryRunner.query(`CREATE TABLE "asset" ("id" SERIAL NOT NULL, "asset_code" character varying(50) NOT NULL, "asset_name" character varying(255) NOT NULL, "price" numeric(15,2), "purchase_date" date, "status" "public"."asset_status_enum" NOT NULL DEFAULT 'NEW', "description" text, "image_url" character varying(500), "current_holder_id" integer, "current_assignment_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "category_id" integer, CONSTRAINT "UQ_d16a4d5dc0a70b531b5b0ee43d1" UNIQUE ("asset_code"), CONSTRAINT "PK_1209d107fe21482beaea51b745e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assignment_history_status_enum" AS ENUM('ASSIGNED', 'RETURNED')`);
        await queryRunner.query(`CREATE TABLE "assignment_history" ("id" SERIAL NOT NULL, "assignment_date" date NOT NULL, "return_date" date, "assignment_reason" text, "return_reason" text, "condition_on_assignment" character varying(100), "condition_on_return" character varying(100), "status" "public"."assignment_history_status_enum" NOT NULL DEFAULT 'ASSIGNED', "note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "asset_id" integer NOT NULL, "employee_id" integer NOT NULL, "assigned_by_id" integer, "returned_by_id" integer, CONSTRAINT "PK_9e3ec8e134976ba55ea4043b7bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."supplier_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "supplier" ("id" SERIAL NOT NULL, "supplier_code" character varying(50) NOT NULL, "supplier_name" character varying(255) NOT NULL, "service_type" character varying(100), "address" text, "phone" character varying(20), "email" character varying(100), "contact_person" character varying(100), "note" text, "status" "public"."supplier_status_enum" NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7f1a06837f963490d84ce48c860" UNIQUE ("supplier_code"), CONSTRAINT "PK_2bc0d2cab6276144d2ff98a2828" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."request_request_type_enum" AS ENUM('PURCHASE', 'REPAIR', 'MAINTENANCE')`);
        await queryRunner.query(`CREATE TYPE "public"."request_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT')`);
        await queryRunner.query(`CREATE TYPE "public"."request_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "request" ("id" SERIAL NOT NULL, "request_type" "public"."request_request_type_enum" NOT NULL, "asset_name_suggest" character varying(255), "quantity" integer NOT NULL DEFAULT '1', "image_url" character varying(500), "reason" text NOT NULL, "request_date" date NOT NULL, "needed_date" date, "priority" "public"."request_priority_enum" NOT NULL DEFAULT 'MEDIUM', "status" "public"."request_status_enum" NOT NULL DEFAULT 'PENDING', "approval_date" date, "rejection_reason" text, "approval_note" text, "estimated_cost" numeric(15,2), "actual_cost" numeric(15,2), "start_date" date, "completion_date" date, "result_note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "requester_id" integer, "category_id" integer, "asset_id" integer, "approver_id" integer, "supplier_id" integer, CONSTRAINT "PK_167d324701e6867f189aed52e18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_notification_type_enum" AS ENUM('NEW_REQUEST', 'APPROVED', 'REJECTED', 'COMPLETED', 'REMINDER')`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" SERIAL NOT NULL, "notification_type" "public"."notification_notification_type_enum" NOT NULL, "title" character varying(255) NOT NULL, "content" text NOT NULL, "link" character varying(500), "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "recipient_id" integer, "request_id" integer, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "issue_assignees" ("issue_id" integer NOT NULL, "employee_id" integer NOT NULL, CONSTRAINT "PK_7636e3e0dbb4ffd554b1c7f8086" PRIMARY KEY ("issue_id", "employee_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f9a83e6965b71c01d5fb6b21ad" ON "issue_assignees" ("issue_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_752f7b18f6778736e2120d576c" ON "issue_assignees" ("employee_id") `);
        await queryRunner.query(`CREATE TABLE "issue_watchers" ("issue_id" integer NOT NULL, "employee_id" integer NOT NULL, CONSTRAINT "PK_7b5f821f502d28f119d605d0b6d" PRIMARY KEY ("issue_id", "employee_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_02472ad904267dfb19ce33f916" ON "issue_watchers" ("issue_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_60b89cd08e261fe7e9fcc3fb5a" ON "issue_watchers" ("employee_id") `);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_roles" ADD CONSTRAINT "FK_04aafdf0252f05451916c4810ec" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_roles" ADD CONSTRAINT "FK_13f42debabcdc155b21632097cf" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_b8b76bed7270f26e59ff5561715" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_d58632e91171a9cb02fc1562383" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_statuses" ADD CONSTRAINT "FK_9a4787836ba925fb9b50d1e3073" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_scheme_mappings" ADD CONSTRAINT "FK_c4ee3959fa2c1270f7e615b11f6" FOREIGN KEY ("issue_type_id") REFERENCES "issue_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_scheme_mappings" ADD CONSTRAINT "FK_e2362b6f481908c0112ffcf721b" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "epics" ADD CONSTRAINT "FK_dc579be47613cc4f616845d0bff" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_11f35e8296e10c229e7b68c68d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_53d9b04f3d8c1fb560cf37fad71" FOREIGN KEY ("issue_type_id") REFERENCES "issue_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_0352f4cbee4c28fd45b9ec70425" FOREIGN KEY ("current_status_id") REFERENCES "workflow_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_394a6ced54c634dfadea1618d2a" FOREIGN KEY ("reporter_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_e05271991458d0c9a69d390ecea" FOREIGN KEY ("epic_link_id") REFERENCES "epics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_links" ADD CONSTRAINT "FK_9ffae1c267c29bdf67f6d5ed3c3" FOREIGN KEY ("source_issue_id") REFERENCES "issues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_links" ADD CONSTRAINT "FK_448d9b37594d9efdf50506086ef" FOREIGN KEY ("target_issue_id") REFERENCES "issues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_comments" ADD CONSTRAINT "FK_5031938a085cb5bea6ed4eaeb53" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_comments" ADD CONSTRAINT "FK_30b9741e8c12c13be895b2a76ea" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_change_histories" ADD CONSTRAINT "FK_2fd936bfb04be33d2e6d2ce7565" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_change_histories" ADD CONSTRAINT "FK_c763d644f1cc226181ab9660a90" FOREIGN KEY ("changer_employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_1e608eb6e2a4645664f0579bd16" FOREIGN KEY ("lead_employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_700b0b13f494cb37b6ca929e79b" FOREIGN KEY ("parent_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_positions" ADD CONSTRAINT "FK_aa29183a0652f1a189b9d7bcc9f" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_positions" ADD CONSTRAINT "FK_1ed32928c6ed87e7cfba6548fc9" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_positions" ADD CONSTRAINT "FK_1f97107ff3fd45a193d7d39761b" FOREIGN KEY ("position_id") REFERENCES "positions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_2be2f615d3c20d620c6485d5463" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_salary" ADD CONSTRAINT "FK_39790bd219da7c30081698fbe77" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_request" ADD CONSTRAINT "FK_f457a5663e14c8aa27ce95a8a6a" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_request" ADD CONSTRAINT "FK_593a5fa4fb099900c9a09bd663b" FOREIGN KEY ("approved_by") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_e4bbac3c88a28f06743194174ae" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_63c92c51cd7fd95c2d79d709b61" FOREIGN KEY ("uploaded_by") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_notifications" ADD CONSTRAINT "FK_3f9e688871180c1f1a51c444a17" FOREIGN KEY ("notification_scheme_id") REFERENCES "notification_schemes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_82145010051f3f2fc94671c0b35" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprint_issues" ADD CONSTRAINT "FK_8136d9e36340485a22ddfe01c75" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprint_issues" ADD CONSTRAINT "FK_492fed54de533f8641b6bc71bc3" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_roles" ADD CONSTRAINT "FK_4684d65a563d66faa66e95c29ae" FOREIGN KEY ("permission_scheme_id") REFERENCES "permission_schemes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_permissions" ADD CONSTRAINT "FK_8da29b131cb3b488bfb8c19dc42" FOREIGN KEY ("permission_scheme_id") REFERENCES "permission_schemes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_permissions" ADD CONSTRAINT "FK_a051e70727479a301696ac99bf9" FOREIGN KEY ("project_role_id") REFERENCES "project_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_permissions" ADD CONSTRAINT "FK_1c50bb3fde65f7da38ac26e1c51" FOREIGN KEY ("specific_employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" ADD CONSTRAINT "FK_996f78c55c0fcdbb2bc4ff8fd0f" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" ADD CONSTRAINT "FK_2922f3e15002c00fffeb19b2c40" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" ADD CONSTRAINT "FK_edfdd606b217aab6b8389390b23" FOREIGN KEY ("project_role_id") REFERENCES "project_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" ADD CONSTRAINT "FK_e47c35197dcf3561fa53c61d4f7" FOREIGN KEY ("assigned_by_employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_9042e8a886f7f83b1de94fee280" FOREIGN KEY ("generated_by") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_devices" ADD CONSTRAINT "FK_d5d3a44de6ea33fd232a7da7748" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_devices" ADD CONSTRAINT "FK_aef9f84ad30a7498fef3c3a6072" FOREIGN KEY ("registered_by") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_challenges" ADD CONSTRAINT "FK_fb566b7a68972562f936d78d1c7" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ADD CONSTRAINT "FK_98b6b8df74fb14ff04085f2a8a8" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "salary_settings" ADD CONSTRAINT "FK_20b87bba1b5b1d45116680d11a4" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD CONSTRAINT "FK_cc55b2f56774c09e8290a0823fa" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "overtime_request" ADD CONSTRAINT "FK_bc788329bde5aee398cc24bf254" FOREIGN KEY ("approved_by") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ADD CONSTRAINT "FK_47601bebe4d909cfbbe8654dd26" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "late_early_request" ADD CONSTRAINT "FK_dfe7175c51413b4f16dcd8d37d8" FOREIGN KEY ("approved_by") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset" ADD CONSTRAINT "FK_34bcae130ac8ab9cb8f738a40f1" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignment_history" ADD CONSTRAINT "FK_619bb815205479c1a5024a76ac6" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignment_history" ADD CONSTRAINT "FK_3ce14f0c213ca343883dc1a3b37" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignment_history" ADD CONSTRAINT "FK_51a1f6448fece19dbc7f4ddf140" FOREIGN KEY ("assigned_by_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignment_history" ADD CONSTRAINT "FK_862d638f370d2cfc24054055029" FOREIGN KEY ("returned_by_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request" ADD CONSTRAINT "FK_30f0550a69bfc4732e291b41557" FOREIGN KEY ("requester_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request" ADD CONSTRAINT "FK_8079798af540d12456087609099" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request" ADD CONSTRAINT "FK_a698ace6b647d7ef2f7f07d39b2" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request" ADD CONSTRAINT "FK_37fbeea78afc8338d79e765889d" FOREIGN KEY ("approver_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request" ADD CONSTRAINT "FK_9fd9ad31c9e67794726ef08722f" FOREIGN KEY ("supplier_id") REFERENCES "supplier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_9830357f52360a126737d498e66" FOREIGN KEY ("recipient_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_5878f4b35143abceccd77125177" FOREIGN KEY ("request_id") REFERENCES "request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_assignees" ADD CONSTRAINT "FK_f9a83e6965b71c01d5fb6b21ad7" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "issue_assignees" ADD CONSTRAINT "FK_752f7b18f6778736e2120d576c1" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_watchers" ADD CONSTRAINT "FK_02472ad904267dfb19ce33f9160" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "issue_watchers" ADD CONSTRAINT "FK_60b89cd08e261fe7e9fcc3fb5a0" FOREIGN KEY ("employee_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "issue_watchers" DROP CONSTRAINT "FK_60b89cd08e261fe7e9fcc3fb5a0"`);
        await queryRunner.query(`ALTER TABLE "issue_watchers" DROP CONSTRAINT "FK_02472ad904267dfb19ce33f9160"`);
        await queryRunner.query(`ALTER TABLE "issue_assignees" DROP CONSTRAINT "FK_752f7b18f6778736e2120d576c1"`);
        await queryRunner.query(`ALTER TABLE "issue_assignees" DROP CONSTRAINT "FK_f9a83e6965b71c01d5fb6b21ad7"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_5878f4b35143abceccd77125177"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_9830357f52360a126737d498e66"`);
        await queryRunner.query(`ALTER TABLE "request" DROP CONSTRAINT "FK_9fd9ad31c9e67794726ef08722f"`);
        await queryRunner.query(`ALTER TABLE "request" DROP CONSTRAINT "FK_37fbeea78afc8338d79e765889d"`);
        await queryRunner.query(`ALTER TABLE "request" DROP CONSTRAINT "FK_a698ace6b647d7ef2f7f07d39b2"`);
        await queryRunner.query(`ALTER TABLE "request" DROP CONSTRAINT "FK_8079798af540d12456087609099"`);
        await queryRunner.query(`ALTER TABLE "request" DROP CONSTRAINT "FK_30f0550a69bfc4732e291b41557"`);
        await queryRunner.query(`ALTER TABLE "assignment_history" DROP CONSTRAINT "FK_862d638f370d2cfc24054055029"`);
        await queryRunner.query(`ALTER TABLE "assignment_history" DROP CONSTRAINT "FK_51a1f6448fece19dbc7f4ddf140"`);
        await queryRunner.query(`ALTER TABLE "assignment_history" DROP CONSTRAINT "FK_3ce14f0c213ca343883dc1a3b37"`);
        await queryRunner.query(`ALTER TABLE "assignment_history" DROP CONSTRAINT "FK_619bb815205479c1a5024a76ac6"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP CONSTRAINT "FK_34bcae130ac8ab9cb8f738a40f1"`);
        await queryRunner.query(`ALTER TABLE "late_early_request" DROP CONSTRAINT "FK_dfe7175c51413b4f16dcd8d37d8"`);
        await queryRunner.query(`ALTER TABLE "late_early_request" DROP CONSTRAINT "FK_47601bebe4d909cfbbe8654dd26"`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP CONSTRAINT "FK_bc788329bde5aee398cc24bf254"`);
        await queryRunner.query(`ALTER TABLE "overtime_request" DROP CONSTRAINT "FK_cc55b2f56774c09e8290a0823fa"`);
        await queryRunner.query(`ALTER TABLE "salary_settings" DROP CONSTRAINT "FK_20b87bba1b5b1d45116680d11a4"`);
        await queryRunner.query(`ALTER TABLE "salary_settings" DROP CONSTRAINT "FK_98b6b8df74fb14ff04085f2a8a8"`);
        await queryRunner.query(`ALTER TABLE "attendance_challenges" DROP CONSTRAINT "FK_fb566b7a68972562f936d78d1c7"`);
        await queryRunner.query(`ALTER TABLE "employee_devices" DROP CONSTRAINT "FK_aef9f84ad30a7498fef3c3a6072"`);
        await queryRunner.query(`ALTER TABLE "employee_devices" DROP CONSTRAINT "FK_d5d3a44de6ea33fd232a7da7748"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_9042e8a886f7f83b1de94fee280"`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" DROP CONSTRAINT "FK_e47c35197dcf3561fa53c61d4f7"`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" DROP CONSTRAINT "FK_edfdd606b217aab6b8389390b23"`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" DROP CONSTRAINT "FK_2922f3e15002c00fffeb19b2c40"`);
        await queryRunner.query(`ALTER TABLE "project_role_assignments" DROP CONSTRAINT "FK_996f78c55c0fcdbb2bc4ff8fd0f"`);
        await queryRunner.query(`ALTER TABLE "project_permissions" DROP CONSTRAINT "FK_1c50bb3fde65f7da38ac26e1c51"`);
        await queryRunner.query(`ALTER TABLE "project_permissions" DROP CONSTRAINT "FK_a051e70727479a301696ac99bf9"`);
        await queryRunner.query(`ALTER TABLE "project_permissions" DROP CONSTRAINT "FK_8da29b131cb3b488bfb8c19dc42"`);
        await queryRunner.query(`ALTER TABLE "project_roles" DROP CONSTRAINT "FK_4684d65a563d66faa66e95c29ae"`);
        await queryRunner.query(`ALTER TABLE "sprint_issues" DROP CONSTRAINT "FK_492fed54de533f8641b6bc71bc3"`);
        await queryRunner.query(`ALTER TABLE "sprint_issues" DROP CONSTRAINT "FK_8136d9e36340485a22ddfe01c75"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_82145010051f3f2fc94671c0b35"`);
        await queryRunner.query(`ALTER TABLE "project_notifications" DROP CONSTRAINT "FK_3f9e688871180c1f1a51c444a17"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_63c92c51cd7fd95c2d79d709b61"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_e4bbac3c88a28f06743194174ae"`);
        await queryRunner.query(`ALTER TABLE "leave_request" DROP CONSTRAINT "FK_593a5fa4fb099900c9a09bd663b"`);
        await queryRunner.query(`ALTER TABLE "leave_request" DROP CONSTRAINT "FK_f457a5663e14c8aa27ce95a8a6a"`);
        await queryRunner.query(`ALTER TABLE "employee_salary" DROP CONSTRAINT "FK_39790bd219da7c30081698fbe77"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_2be2f615d3c20d620c6485d5463"`);
        await queryRunner.query(`ALTER TABLE "employee_positions" DROP CONSTRAINT "FK_1f97107ff3fd45a193d7d39761b"`);
        await queryRunner.query(`ALTER TABLE "employee_positions" DROP CONSTRAINT "FK_1ed32928c6ed87e7cfba6548fc9"`);
        await queryRunner.query(`ALTER TABLE "employee_positions" DROP CONSTRAINT "FK_aa29183a0652f1a189b9d7bcc9f"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_700b0b13f494cb37b6ca929e79b"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_1e608eb6e2a4645664f0579bd16"`);
        await queryRunner.query(`ALTER TABLE "issue_change_histories" DROP CONSTRAINT "FK_c763d644f1cc226181ab9660a90"`);
        await queryRunner.query(`ALTER TABLE "issue_change_histories" DROP CONSTRAINT "FK_2fd936bfb04be33d2e6d2ce7565"`);
        await queryRunner.query(`ALTER TABLE "issue_comments" DROP CONSTRAINT "FK_30b9741e8c12c13be895b2a76ea"`);
        await queryRunner.query(`ALTER TABLE "issue_comments" DROP CONSTRAINT "FK_5031938a085cb5bea6ed4eaeb53"`);
        await queryRunner.query(`ALTER TABLE "issue_links" DROP CONSTRAINT "FK_448d9b37594d9efdf50506086ef"`);
        await queryRunner.query(`ALTER TABLE "issue_links" DROP CONSTRAINT "FK_9ffae1c267c29bdf67f6d5ed3c3"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_e05271991458d0c9a69d390ecea"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_394a6ced54c634dfadea1618d2a"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_0352f4cbee4c28fd45b9ec70425"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_53d9b04f3d8c1fb560cf37fad71"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_11f35e8296e10c229e7b68c68d4"`);
        await queryRunner.query(`ALTER TABLE "epics" DROP CONSTRAINT "FK_dc579be47613cc4f616845d0bff"`);
        await queryRunner.query(`ALTER TABLE "workflow_scheme_mappings" DROP CONSTRAINT "FK_e2362b6f481908c0112ffcf721b"`);
        await queryRunner.query(`ALTER TABLE "workflow_scheme_mappings" DROP CONSTRAINT "FK_c4ee3959fa2c1270f7e615b11f6"`);
        await queryRunner.query(`ALTER TABLE "workflow_statuses" DROP CONSTRAINT "FK_9a4787836ba925fb9b50d1e3073"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_d58632e91171a9cb02fc1562383"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_b8b76bed7270f26e59ff5561715"`);
        await queryRunner.query(`ALTER TABLE "employee_roles" DROP CONSTRAINT "FK_13f42debabcdc155b21632097cf"`);
        await queryRunner.query(`ALTER TABLE "employee_roles" DROP CONSTRAINT "FK_04aafdf0252f05451916c4810ec"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60b89cd08e261fe7e9fcc3fb5a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02472ad904267dfb19ce33f916"`);
        await queryRunner.query(`DROP TABLE "issue_watchers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_752f7b18f6778736e2120d576c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9a83e6965b71c01d5fb6b21ad"`);
        await queryRunner.query(`DROP TABLE "issue_assignees"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TYPE "public"."notification_notification_type_enum"`);
        await queryRunner.query(`DROP TABLE "request"`);
        await queryRunner.query(`DROP TYPE "public"."request_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."request_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."request_request_type_enum"`);
        await queryRunner.query(`DROP TABLE "supplier"`);
        await queryRunner.query(`DROP TYPE "public"."supplier_status_enum"`);
        await queryRunner.query(`DROP TABLE "assignment_history"`);
        await queryRunner.query(`DROP TYPE "public"."assignment_history_status_enum"`);
        await queryRunner.query(`DROP TABLE "asset"`);
        await queryRunner.query(`DROP TYPE "public"."asset_status_enum"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "late_early_request"`);
        await queryRunner.query(`DROP TYPE "public"."late_early_request_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."late_early_request_type_enum"`);
        await queryRunner.query(`DROP TABLE "overtime_request"`);
        await queryRunner.query(`DROP TYPE "public"."overtime_request_status_enum"`);
        await queryRunner.query(`DROP TABLE "salary_settings"`);
        await queryRunner.query(`DROP TABLE "work_schedule_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c97acd2690919ebfd0d611ac2e"`);
        await queryRunner.query(`DROP TABLE "attendance_challenges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37689c8b97d053209a3df8b33f"`);
        await queryRunner.query(`DROP TABLE "employee_devices"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f5d2a3e6fa219263371ae8770"`);
        await queryRunner.query(`DROP TABLE "project_role_assignments"`);
        await queryRunner.query(`DROP TABLE "project_permissions"`);
        await queryRunner.query(`DROP TABLE "project_roles"`);
        await queryRunner.query(`DROP TABLE "permission_schemes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14ea8d57167fbfb24774c401b4"`);
        await queryRunner.query(`DROP TABLE "sprint_issues"`);
        await queryRunner.query(`DROP TABLE "sprints"`);
        await queryRunner.query(`DROP TABLE "project_notifications"`);
        await queryRunner.query(`DROP TABLE "notification_schemes"`);
        await queryRunner.query(`DROP TABLE "employee"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TABLE "leave_request"`);
        await queryRunner.query(`DROP TABLE "employee_salary"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TABLE "employee_positions"`);
        await queryRunner.query(`DROP TABLE "positions"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TABLE "issue_change_histories"`);
        await queryRunner.query(`DROP TABLE "issue_comments"`);
        await queryRunner.query(`DROP TABLE "issue_links"`);
        await queryRunner.query(`DROP TABLE "issues"`);
        await queryRunner.query(`DROP TABLE "epics"`);
        await queryRunner.query(`DROP TABLE "issue_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ff2c1c4c5668bda6cadc4eca8"`);
        await queryRunner.query(`DROP TABLE "workflow_scheme_mappings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38b7a83f7dad794d535bb1c82d"`);
        await queryRunner.query(`DROP TABLE "workflow_statuses"`);
        await queryRunner.query(`DROP TABLE "workflow_schemes"`);
        await queryRunner.query(`DROP TABLE "workflows"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "employee_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
    }

}
